using System.Text;

namespace SqliteReader.Tests;

/// <summary>
/// Reads payloads that spill onto overflow pages. The values are generated by create-test-databases.sh as
/// substr(group_concat(i * seed, ','), 1, length) for i = 1..length.
/// </summary>
public class OverflowTests
{
    [TestCase("overflow512.db")]
    [TestCase("overflow4096.db")]
    public async Task RowIdTable_ValuesMatchGeneratedContent(string file)
    {
        await using var database = await SqliteDatabase.OpenAsync(TestData.Path(file));
        long previous = -1;
        int count = 0;

        await foreach (var row in database.ReadTableAsync("t"))
        {
            long length = (long)row["len"]!;
            Assert.Multiple(() =>
            {
                Assert.That(row.RowId, Is.EqualTo(length));
                Assert.That(row["id"], Is.EqualTo(length));
                Assert.That(length, Is.GreaterThan(previous));
                Assert.That(row["txt"], Is.EqualTo(Generate((int)length, 3)), $"txt of length {length}");
                Assert.That(row["blb"], Is.EqualTo(Encoding.UTF8.GetBytes(Generate((int)length, 7))), $"blb of length {length}");
            });
            previous = length;
            count++;
        }

        Assert.That(count, Is.GreaterThan(100));
        Assert.That(previous, Is.EqualTo(1_000_000));
    }

    [TestCase("overflow512.db")]
    [TestCase("overflow4096.db")]
    public async Task WithoutRowIdTable_KeysMatchGeneratedContent(string file)
    {
        await using var database = await SqliteDatabase.OpenAsync(TestData.Path(file));
        string? previous = null;
        int count = 0;

        await foreach (var row in database.ReadTableAsync("w"))
        {
            long length = (long)row["len"]!;
            string key = (string)row["k"]!;
            Assert.Multiple(() =>
            {
                Assert.That(row.RowId, Is.Null);
                Assert.That(key, Is.EqualTo($"{length:D8}:" + Generate((int)length, 5)));
                Assert.That(string.CompareOrdinal(key, previous), Is.GreaterThan(0), "keys must be in ascending order");
            });
            previous = key;
            count++;
        }

        Assert.That(count, Is.GreaterThan(100));
    }

    private static string Generate(int length, int seed)
    {
        var sb = new StringBuilder(length + 16);
        for (int i = 1; sb.Length < length; i++)
        {
            if (i > 1)
            {
                sb.Append(',');
            }

            sb.Append(i * seed);
        }

        return sb.ToString(0, length);
    }
}
